// Offline generator for src/asciiShapes/shapeVectors.ts.
//
// For each printable-ASCII glyph in the unscii-16 bitmap font, partition the
// cell into a 2-col x 3-row grid of 6 regions and measure per-region ink
// coverage, producing a 6D shape vector. After all glyphs are measured, every
// component is normalized by the single global-max raw component so the table's
// largest normalized component is 1.0. The result is written as a generated
// constant so the library keeps its zero-runtime-dependency guarantee.
//
// Sampling geometry MUST stay byte-for-byte identical to the runtime sampler in
// CellRenderer, so the region grid constants are imported from the shared
// module rather than duplicated here.
//
// Run with: pnpm generate:ascii-shapes  (node scripts/generateAsciiShapes/index.ts)

import { writeFileSync } from 'node:fs';
import {
  SHAPE_REGION_COLS,
  SHAPE_REGION_ROWS,
  SHAPE_VECTOR_DIMS,
} from '../../src/asciiShapes/consts.ts';
import {
  UNSCII16_ASCII_GLYPHS,
  UNSCII16_CELL_WIDTH,
  UNSCII16_CELL_HEIGHT,
  UNSCII16_FIRST_CODEPOINT,
} from './unsciiFont.ts';

const HEX_RADIX = 16;
const HEX_CHARS_PER_BYTE = 2;
const DECIMAL_PLACES = 6;

const BANNER =
  '// GENERATED by scripts/generateAsciiShapes — DO NOT EDIT. ' +
  'Run `pnpm generate:ascii-shapes` to regenerate.';

// Region index for a pixel by its center, matching the runtime invariant:
// col = min(COLS-1, floor((px+0.5)/W * COLS)), row = min(ROWS-1, floor((py+0.5)/H * ROWS)),
// region = row * COLS + col. Polarity is ink coverage (bit set = 1), no inversion.
const regionOf = (px: number, py: number): number => {
  const col = Math.min(
    SHAPE_REGION_COLS - 1,
    Math.floor(((px + 0.5) / UNSCII16_CELL_WIDTH) * SHAPE_REGION_COLS),
  );
  const row = Math.min(
    SHAPE_REGION_ROWS - 1,
    Math.floor(((py + 0.5) / UNSCII16_CELL_HEIGHT) * SHAPE_REGION_ROWS),
  );
  return row * SHAPE_REGION_COLS + col;
};

// Decode one glyph's hex rows into its raw per-region mean ink coverage vector.
const rawVectorFor = (glyph: string): number[] => {
  const sums = new Array<number>(SHAPE_VECTOR_DIMS).fill(0);
  const counts = new Array<number>(SHAPE_VECTOR_DIMS).fill(0);
  for (let py = 0; py < UNSCII16_CELL_HEIGHT; py++) {
    const rowByte = parseInt(
      glyph.slice(py * HEX_CHARS_PER_BYTE, py * HEX_CHARS_PER_BYTE + HEX_CHARS_PER_BYTE),
      HEX_RADIX,
    );
    for (let px = 0; px < UNSCII16_CELL_WIDTH; px++) {
      // Most-significant bit is the leftmost pixel.
      const bit = (rowByte >> (UNSCII16_CELL_WIDTH - 1 - px)) & 1;
      const region = regionOf(px, py);
      sums[region] += bit;
      counts[region] += 1;
    }
  }
  return sums.map((sum, i) => sum / counts[i]);
};

// Round to DECIMAL_PLACES and normalize -0 to 0 so output is stable.
const round = (value: number): number => {
  const rounded = Number(value.toFixed(DECIMAL_PLACES));
  return rounded === 0 ? 0 : rounded;
};

// A single-quoted JS string literal for one glyph, escaping only the two chars
// that need it inside single quotes (backslash and single quote). Single quotes
// keep the generated file consistent with the repo's quote lint rule.
const charLiteral = (char: string): string =>
  `'${char.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const rawVectors = UNSCII16_ASCII_GLYPHS.map(rawVectorFor);

let globalMax = 0;
for (const vector of rawVectors) {
  for (const component of vector) {
    if (component > globalMax) {
      globalMax = component;
    }
  }
}

const normalize = (component: number): number =>
  globalMax > 0 ? component / globalMax : component;

const entries = rawVectors.map((vector, i) => {
  const char = String.fromCodePoint(UNSCII16_FIRST_CODEPOINT + i);
  const normalized = vector.map((component) => round(normalize(component)));
  return `  { char: ${charLiteral(char)}, vector: [${normalized.join(', ')}] },`;
});

const content = [
  BANNER,
  '/* eslint-disable @typescript-eslint/no-magic-numbers */',
  "import type { AsciiShape } from './types.ts';",
  '',
  'export const ASCII_SHAPES: readonly AsciiShape[] = [',
  ...entries,
  '];',
  '',
].join('\n');

const outputUrl = new URL('../../src/asciiShapes/shapeVectors.ts', import.meta.url);
writeFileSync(outputUrl, content);

process.stdout.write(
  `Wrote ${entries.length} shapes to src/asciiShapes/shapeVectors.ts (global max raw = ${globalMax}).\n`,
);
