/**
 * Per-frame metadata for encoding one frame into a Kitty graphics payload.
 *
 * Every frame is fully self-describing so the encoder (and the worker thread
 * wrapping it) never needs configuration sync when settings change at runtime.
 */
import type { Rect } from '../dirtyRect/index.ts';

const isPlainObject = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);
const isString = (value: unknown): value is string => typeof value === 'string';

export interface KittyFrameMeta {
  sourceWidth: number;
  sourceHeight: number;
  scale: number;
  scaledWidth: number;
  scaledHeight: number;
  pngCompressionLevel: number;
  // Kitty placement: display size in terminal cells and cursor position
  displayCols: number;
  displayRows: number;
  offsetRow: number;
  offsetCol: number;
  // Alternating image ids provide a double-buffering effect
  currentImageId: number;
  previousImageId: number;
  deletePrevious: boolean;
  /** 'full' transmits and displays a new image (a=T); 'delta' edits the displayed image in place (a=f) */
  transmit: 'full' | 'delta';
  /** Region of the source frame to encode, in source pixel coordinates (the whole frame when transmit is 'full') */
  dirtyRect: Rect;
  /** How the payload travels: 'escape' embeds base64 data in the escape sequence (chunked), 'file' writes a temp file and sends its base64 path (t=t, terminal-deleted) */
  medium: 'escape' | 'file';
  /** Destination for the PNG when medium is 'file'; generated by the renderer so the main thread can clean up dropped frames */
  filePath?: string;
}

/**
 * Worker protocol: the main thread transfers the frame's RGB pixels to the
 * worker; the worker transfers the same ArrayBuffer back with the encoded
 * payload so the main thread can recycle it (zero steady-state allocation).
 */
export interface KittyEncodeRequest {
  type: 'encode';
  meta: KittyFrameMeta;
  rgb: ArrayBuffer;
}

export interface KittyEncodeResponse {
  type: 'encoded';
  payload: string;
  rgb: ArrayBuffer;
}

export const isKittyEncodeRequest = (value: unknown): value is KittyEncodeRequest =>
  isPlainObject(value) &&
  value.type === 'encode' &&
  isPlainObject(value.meta) &&
  value.rgb instanceof ArrayBuffer;

export const isKittyEncodeResponse = (value: unknown): value is KittyEncodeResponse =>
  isPlainObject(value) &&
  value.type === 'encoded' &&
  isString(value.payload) &&
  value.rgb instanceof ArrayBuffer;

export type { Rect } from '../dirtyRect/index.ts';

/**
 * The subset of frame metadata the PNG-encoding path reads. A full
 * KittyFrameMeta satisfies it structurally, and standalone image encoding
 * (screenshots via KittyFrameEncoder.encodeImage) supplies just these two.
 */
export interface PngEncodeParams {
  /** Output scale relative to the source buffer (1 = native resolution) */
  scale: number;
  /** Deflate level for the PNG IDAT chunk (1-9, higher = smaller and slower) */
  pngCompressionLevel: number;
}

// Rect-resolved encoding input: the (possibly cropped) source pixels and
// their scaled output dimensions and placement within the full image
export interface EncodeJob {
  rgb: Uint8Array;
  sourceWidth: number;
  sourceHeight: number;
  scaledWidth: number;
  scaledHeight: number;
  scaledX: number;
  scaledY: number;
}
